spring.application.name=finanzas
# Conexión a la base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/finanzas_db?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=apoud21

# Hibernate (La magia que transforma objetos Java en tablas SQL)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8081